version: '3.8'

services:
  products:
    build: 
      context: "./product-service"
    ports:
      - "8081:8081"

  order:
    build:
      context: "./order-service"
    ports:
      - "8082:8082"
    depends_on:
      - products